### PR TITLE
Add description of what save function does depending if book exists

### PR DESCRIPTION
**Pull request by fermolanoc**
@saida93522 This code adds a comment describing what save function does on bookstore.py file.
Details of how function works are provided depending if function finds an id, which means that book already exists, or not which means a new book is trying to be added. This fixes issue #7 
Thanks.

### CODE REVIEW

**Comment by saida93522** [comment]
It looks great, much more user friendly. ready to merge.

**Comment by saida93522** [comment]
I think description works, however I would suggest fixing the lines. 
""write an overall description on a single line,
:The rest of description here.""".
also write documentation inside the code you want to document. so for this case inside the def statement. check out the bookstore functions for example.

**Comment by fermolanoc** [comment]
Thanks for the feedback. I simplified function description and re-organized it including it also inside function block.

**Comment by claraj** [comment]
Looks good!

**Pull request merged**
